theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
separator = "►"
left = ["mode", "spinner", "version-control", "separator", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position"]

[editor.file-picker]
hidden = false
git-ignore = false

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"